version: '3.9'

services:
  base: &base
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp:cached
      - bundler_gems:/usr/local/bundle/
      - node_modules:/myapp/node_modules
    depends_on:
      - redis
      - db

  web:
    <<: *base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'

  css:
    <<: *base
    command: yarn build:css --watch

  js:
    <<: *base
    command: yarn build --watch

  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: always

  db:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
       - 5432:5432

  # sidekiq:
  #   <<: *base
  #   command: bundle exec sidekiq
  
volumes:
  postgres:
  redis:
  bundler_gems:
  node_modules: